const projectItems = [
    {
        id:0,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"https://www.youtube.com/embed/fEErySYqItI?si=9ZoskEo5CuR4xOJ6",
        title:"LOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:1,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"https://www.youtube.com/embed/SVB66nWk9dQ?si=etdV4GUa6y9pbFth",
        title:"LOREMT",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:2,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:3,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:4,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:5,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:6,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:7,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:8,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:9,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:10,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
]


export default projectItems;