const projectItems = [
    {
        id:0,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/pages/videos/Proximity.mp4",
        title:"LOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:1,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"LOREMT",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:2,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    },
    {
        id:3,
        imgURL:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        videoURL:"../src/assets/videos/Proximity.mp4",
        title:"TTLOREM",
        slide1:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide2:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide3:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide4:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png",
        slide5:"https://www.springboard.com/blog/wp-content/uploads/2022/04/saas-dashboard-1.png"
    }
]


export default projectItems;